apiVersion: v1
kind: Namespace
metadata:
  name: hyperion
spec: {}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hyperion-daemon
  namespace: hyperion
  labels:
    app: hyperion-daemon
    core.hyperion.io/master: "true"
spec:
  selector:
    matchLabels:
      app: hyperion-daemon
  template:
    metadata:
      labels:
        app: hyperion-daemon
        core.hyperion.io/master: "true"
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: hyperion-daemon
          image: utkarsh23/hyperion:v0.0.1
          ports:
            - containerPort: 2310
          env:
            - name: RUST_LOG
              value: trace
          securityContext:
            privileged: true
            runAsGroup: 0
            runAsUser: 0
          volumeMounts:
            - name: host-proc-fs
              mountPath: /hostfs/procfs
            - name: host-modules
              mountPath: /lib/modules
            - name: host-sys
              mountPath: /sys
            - name: host-usr-src
              mountPath: /usr/src
      volumes:
        - name: host-proc-fs
          hostPath:
            path: /hostfs/procfs
        - name: host-modules
          hostPath:
            path: /lib/modules
        - name: host-sys
          hostPath:
            path: /sys
        - name: host-usr-src
          hostPath:
            path: /usr/src
      terminationGracePeriodSeconds: 10
