// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: v1alpha1/base/base.proto

package base

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Module struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Core     *ModuleCore     `protobuf:"bytes,1,opt,name=core,proto3" json:"core,omitempty"`
	Metadata *ModuleMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Uid      string          `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Spec     *ModuleSpec     `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	Status   *ModuleStatus   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *Module) Reset() {
	*x = Module{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_base_base_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_base_base_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_v1alpha1_base_base_proto_rawDescGZIP(), []int{0}
}

func (x *Module) GetCore() *ModuleCore {
	if x != nil {
		return x.Core
	}
	return nil
}

func (x *Module) GetMetadata() *ModuleMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Module) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Module) GetSpec() *ModuleSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Module) GetStatus() *ModuleStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type ModuleCore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ModuleCore) Reset() {
	*x = ModuleCore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_base_base_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleCore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleCore) ProtoMessage() {}

func (x *ModuleCore) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_base_base_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleCore.ProtoReflect.Descriptor instead.
func (*ModuleCore) Descriptor() ([]byte, []int) {
	return file_v1alpha1_base_base_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleCore) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ModuleMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Labels  map[string]string        `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Release *ModuleMetadata_Releases `protobuf:"bytes,2,opt,name=release,proto3" json:"release,omitempty"`
}

func (x *ModuleMetadata) Reset() {
	*x = ModuleMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_base_base_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleMetadata) ProtoMessage() {}

func (x *ModuleMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_base_base_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleMetadata.ProtoReflect.Descriptor instead.
func (*ModuleMetadata) Descriptor() ([]byte, []int) {
	return file_v1alpha1_base_base_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ModuleMetadata) GetRelease() *ModuleMetadata_Releases {
	if x != nil {
		return x.Release
	}
	return nil
}

type ModuleSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data       string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	DataSource *ModuleSpec_DataSource `protobuf:"bytes,2,opt,name=dataSource,proto3" json:"dataSource,omitempty"`
}

func (x *ModuleSpec) Reset() {
	*x = ModuleSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_base_base_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleSpec) ProtoMessage() {}

func (x *ModuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_base_base_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleSpec.ProtoReflect.Descriptor instead.
func (*ModuleSpec) Descriptor() ([]byte, []int) {
	return file_v1alpha1_base_base_proto_rawDescGZIP(), []int{3}
}

func (x *ModuleSpec) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *ModuleSpec) GetDataSource() *ModuleSpec_DataSource {
	if x != nil {
		return x.DataSource
	}
	return nil
}

type ModuleStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ModuleStatus) Reset() {
	*x = ModuleStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_base_base_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStatus) ProtoMessage() {}

func (x *ModuleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_base_base_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStatus.ProtoReflect.Descriptor instead.
func (*ModuleStatus) Descriptor() ([]byte, []int) {
	return file_v1alpha1_base_base_proto_rawDescGZIP(), []int{4}
}

func (x *ModuleStatus) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type LabelSelector struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selector map[string]string `protobuf:"bytes,1,rep,name=selector,proto3" json:"selector,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *LabelSelector) Reset() {
	*x = LabelSelector{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_base_base_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabelSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSelector) ProtoMessage() {}

func (x *LabelSelector) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_base_base_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSelector.ProtoReflect.Descriptor instead.
func (*LabelSelector) Descriptor() ([]byte, []int) {
	return file_v1alpha1_base_base_proto_rawDescGZIP(), []int{5}
}

func (x *LabelSelector) GetSelector() map[string]string {
	if x != nil {
		return x.Selector
	}
	return nil
}

type ModuleMetadata_Releases struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinuxAMD64 *ModuleMetadata_Releases_ModuleRelease `protobuf:"bytes,1,opt,name=linuxAMD64,proto3" json:"linuxAMD64,omitempty"`
	LinuxARM64 *ModuleMetadata_Releases_ModuleRelease `protobuf:"bytes,2,opt,name=linuxARM64,proto3" json:"linuxARM64,omitempty"`
}

func (x *ModuleMetadata_Releases) Reset() {
	*x = ModuleMetadata_Releases{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_base_base_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleMetadata_Releases) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleMetadata_Releases) ProtoMessage() {}

func (x *ModuleMetadata_Releases) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_base_base_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleMetadata_Releases.ProtoReflect.Descriptor instead.
func (*ModuleMetadata_Releases) Descriptor() ([]byte, []int) {
	return file_v1alpha1_base_base_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ModuleMetadata_Releases) GetLinuxAMD64() *ModuleMetadata_Releases_ModuleRelease {
	if x != nil {
		return x.LinuxAMD64
	}
	return nil
}

func (x *ModuleMetadata_Releases) GetLinuxARM64() *ModuleMetadata_Releases_ModuleRelease {
	if x != nil {
		return x.LinuxARM64
	}
	return nil
}

type ModuleMetadata_Releases_ModuleRelease struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location string `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Sha256   string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
}

func (x *ModuleMetadata_Releases_ModuleRelease) Reset() {
	*x = ModuleMetadata_Releases_ModuleRelease{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_base_base_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleMetadata_Releases_ModuleRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleMetadata_Releases_ModuleRelease) ProtoMessage() {}

func (x *ModuleMetadata_Releases_ModuleRelease) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_base_base_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleMetadata_Releases_ModuleRelease.ProtoReflect.Descriptor instead.
func (*ModuleMetadata_Releases_ModuleRelease) Descriptor() ([]byte, []int) {
	return file_v1alpha1_base_base_proto_rawDescGZIP(), []int{2, 0, 0}
}

func (x *ModuleMetadata_Releases_ModuleRelease) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *ModuleMetadata_Releases_ModuleRelease) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type ModuleSpec_DataSource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label *LabelSelector `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
}

func (x *ModuleSpec_DataSource) Reset() {
	*x = ModuleSpec_DataSource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1alpha1_base_base_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModuleSpec_DataSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleSpec_DataSource) ProtoMessage() {}

func (x *ModuleSpec_DataSource) ProtoReflect() protoreflect.Message {
	mi := &file_v1alpha1_base_base_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleSpec_DataSource.ProtoReflect.Descriptor instead.
func (*ModuleSpec_DataSource) Descriptor() ([]byte, []int) {
	return file_v1alpha1_base_base_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ModuleSpec_DataSource) GetLabel() *LabelSelector {
	if x != nil {
		return x.Label
	}
	return nil
}

var File_v1alpha1_base_base_proto protoreflect.FileDescriptor

var file_v1alpha1_base_base_proto_rawDesc = []byte{
	0x0a, 0x18, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f, 0x62, 0x61, 0x73, 0x65, 0x2f,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x68, 0x79, 0x70, 0x65,
	0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x62, 0x61,
	0x73, 0x65, 0x22, 0x8c, 0x02, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x36, 0x0a,
	0x04, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x79,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x52,
	0x04, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x42, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x79, 0x70, 0x65,
	0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x62, 0x61,
	0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53, 0x70, 0x65, 0x63, 0x52, 0x04, 0x73,
	0x70, 0x65, 0x63, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x20, 0x0a, 0x0a, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xf2, 0x03, 0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x4a, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x32, 0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x12, 0x49, 0x0a, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x76,
	0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x73, 0x52, 0x07, 0x72, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x1a, 0x8d, 0x02,
	0x0a, 0x08, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x12, 0x5d, 0x0a, 0x0a, 0x6c, 0x69,
	0x6e, 0x75, 0x78, 0x41, 0x4d, 0x44, 0x36, 0x34, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3d,
	0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x2e,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x0a, 0x6c,
	0x69, 0x6e, 0x75, 0x78, 0x41, 0x4d, 0x44, 0x36, 0x34, 0x12, 0x5d, 0x0a, 0x0a, 0x6c, 0x69, 0x6e,
	0x75, 0x78, 0x41, 0x52, 0x4d, 0x36, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3d, 0x2e,
	0x68, 0x79, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61,
	0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x73, 0x2e, 0x4d,
	0x6f, 0x64, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x52, 0x0a, 0x6c, 0x69,
	0x6e, 0x75, 0x78, 0x41, 0x52, 0x4d, 0x36, 0x34, 0x1a, 0x43, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x75,
	0x6c, 0x65, 0x52, 0x65, 0x6c, 0x65, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x1a, 0x39, 0x0a,
	0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xba, 0x01, 0x0a, 0x0a, 0x4d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x4d, 0x0a, 0x0a, 0x64,
	0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x2d, 0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70,
	0x68, 0x61, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53,
	0x70, 0x65, 0x63, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x0a,
	0x64, 0x61, 0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x1a, 0x49, 0x0a, 0x0a, 0x44, 0x61,
	0x74, 0x61, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x3b, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x68, 0x79, 0x70, 0x65, 0x72, 0x69,
	0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x62, 0x61, 0x73, 0x65,
	0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x22, 0x20, 0x0a, 0x0c, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x9d, 0x01, 0x0a, 0x0d, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x4f, 0x0a, 0x08, 0x73, 0x65, 0x6c,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x68, 0x79,
	0x70, 0x65, 0x72, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e,
	0x62, 0x61, 0x73, 0x65, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x53, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x1a, 0x3b, 0x0a, 0x0d, 0x53, 0x65,
	0x6c, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x61, 0x67, 0x61, 0x63, 0x69, 0x6f, 0x75, 0x73, 0x2d,
	0x6c, 0x61, 0x62, 0x73, 0x2f, 0x6b, 0x38, 0x74, 0x72, 0x69, 0x63, 0x73, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31,
	0x2f, 0x62, 0x61, 0x73, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1alpha1_base_base_proto_rawDescOnce sync.Once
	file_v1alpha1_base_base_proto_rawDescData = file_v1alpha1_base_base_proto_rawDesc
)

func file_v1alpha1_base_base_proto_rawDescGZIP() []byte {
	file_v1alpha1_base_base_proto_rawDescOnce.Do(func() {
		file_v1alpha1_base_base_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1alpha1_base_base_proto_rawDescData)
	})
	return file_v1alpha1_base_base_proto_rawDescData
}

var file_v1alpha1_base_base_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_v1alpha1_base_base_proto_goTypes = []interface{}{
	(*Module)(nil),                  // 0: hyperion.v1alpha1.base.Module
	(*ModuleCore)(nil),              // 1: hyperion.v1alpha1.base.ModuleCore
	(*ModuleMetadata)(nil),          // 2: hyperion.v1alpha1.base.ModuleMetadata
	(*ModuleSpec)(nil),              // 3: hyperion.v1alpha1.base.ModuleSpec
	(*ModuleStatus)(nil),            // 4: hyperion.v1alpha1.base.ModuleStatus
	(*LabelSelector)(nil),           // 5: hyperion.v1alpha1.base.LabelSelector
	(*ModuleMetadata_Releases)(nil), // 6: hyperion.v1alpha1.base.ModuleMetadata.Releases
	nil,                             // 7: hyperion.v1alpha1.base.ModuleMetadata.LabelsEntry
	(*ModuleMetadata_Releases_ModuleRelease)(nil), // 8: hyperion.v1alpha1.base.ModuleMetadata.Releases.ModuleRelease
	(*ModuleSpec_DataSource)(nil),                 // 9: hyperion.v1alpha1.base.ModuleSpec.DataSource
	nil,                                           // 10: hyperion.v1alpha1.base.LabelSelector.SelectorEntry
}
var file_v1alpha1_base_base_proto_depIdxs = []int32{
	1,  // 0: hyperion.v1alpha1.base.Module.core:type_name -> hyperion.v1alpha1.base.ModuleCore
	2,  // 1: hyperion.v1alpha1.base.Module.metadata:type_name -> hyperion.v1alpha1.base.ModuleMetadata
	3,  // 2: hyperion.v1alpha1.base.Module.spec:type_name -> hyperion.v1alpha1.base.ModuleSpec
	4,  // 3: hyperion.v1alpha1.base.Module.status:type_name -> hyperion.v1alpha1.base.ModuleStatus
	7,  // 4: hyperion.v1alpha1.base.ModuleMetadata.labels:type_name -> hyperion.v1alpha1.base.ModuleMetadata.LabelsEntry
	6,  // 5: hyperion.v1alpha1.base.ModuleMetadata.release:type_name -> hyperion.v1alpha1.base.ModuleMetadata.Releases
	9,  // 6: hyperion.v1alpha1.base.ModuleSpec.dataSource:type_name -> hyperion.v1alpha1.base.ModuleSpec.DataSource
	10, // 7: hyperion.v1alpha1.base.LabelSelector.selector:type_name -> hyperion.v1alpha1.base.LabelSelector.SelectorEntry
	8,  // 8: hyperion.v1alpha1.base.ModuleMetadata.Releases.linuxAMD64:type_name -> hyperion.v1alpha1.base.ModuleMetadata.Releases.ModuleRelease
	8,  // 9: hyperion.v1alpha1.base.ModuleMetadata.Releases.linuxARM64:type_name -> hyperion.v1alpha1.base.ModuleMetadata.Releases.ModuleRelease
	5,  // 10: hyperion.v1alpha1.base.ModuleSpec.DataSource.label:type_name -> hyperion.v1alpha1.base.LabelSelector
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_v1alpha1_base_base_proto_init() }
func file_v1alpha1_base_base_proto_init() {
	if File_v1alpha1_base_base_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1alpha1_base_base_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Module); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_base_base_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleCore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_base_base_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_base_base_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_base_base_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_base_base_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabelSelector); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_base_base_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleMetadata_Releases); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_base_base_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleMetadata_Releases_ModuleRelease); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1alpha1_base_base_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ModuleSpec_DataSource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1alpha1_base_base_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1alpha1_base_base_proto_goTypes,
		DependencyIndexes: file_v1alpha1_base_base_proto_depIdxs,
		MessageInfos:      file_v1alpha1_base_base_proto_msgTypes,
	}.Build()
	File_v1alpha1_base_base_proto = out.File
	file_v1alpha1_base_base_proto_rawDesc = nil
	file_v1alpha1_base_base_proto_goTypes = nil
	file_v1alpha1_base_base_proto_depIdxs = nil
}
